export enum Keys {
  APP_PORT = 'APP_PORT',
  APP_NAME = 'APP_NAME',
  MONGO_HOST = 'MONGO_HOST',
  MONGO_USERNAME = 'MONGO_USERNAME',
  MONGO_PASSWORD = 'MONGO_PASSWORD',
  MONGO_PORT = 'MONGO_PORT',
  MONGO_DATABASE = 'MONGO_DATABASE',
}
